spring:
  config:
    import: optional:file:.env[.properties]
  opensearch:
    uris: ${OPENSEARCH_URIS:http://localhost:9200}
  datasource:
    url: jdbc:mysql://${DB_ADDRESS}/boardpractice?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_URI}
      port: 6379