spring:
  application:
    name: board-practice
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:h2:file:~/h2db/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: create   # 개발 중에는 create / create-drop / update 중 선택
    properties:
      hibernate:
        format_sql: true
upload:
  directory: ./uploads

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE