name: Deploy to EC2 with Docker Compose

on:
  workflow_dispatch:
  push:
    branches:
      - main  # main 브랜치에 push 될 때 자동 배포

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get GitHub Actions IP성
        id: ip
        uses: haythem/public-ip@v1.3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Add IP to Security Group
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id sg-03f8a7da49f40909e \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SSH and Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. 프로젝트 폴더로 이동 (본인의 EC2 프로젝트 경로로 변경해주세요)
            cd /home/ec2-user/boardproject

            # 2. 최신 코드 불러오기
            git pull origin main

            # 3. [선택] EC2 상에서 백엔드 미리 빌드 (도커 OOM 방지용)
            cd board-practice && ./gradlew build -x test && cd ..

            # 4. 도커 쓰레기 캐시 정량 청소 (용량 부족 방지)
            sudo docker system prune -f

            # 5. 도커 컴포즈 재시동 및 빌드
            sudo docker compose up -d --build
      - name: Remove IP from Security Group (Always Run)
        if: always()
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id sg-03f8a7da49f40909e \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
